README.md
Build badge and install steps, to get things going, should have an npm
badge once we're publishing this on npm. But not yet, as we need to
ensure that everything works
=> docs(README): add basic presentation

global/index.d.ts
This allows the Events to be used directly, as they should
The `onMessage` event now enforces the contract on `boolean` and
`Promise` correctly
=> Fix(runtime): interface

README.md, global/index.d.ts
No missing feature in this API compared to chromium
Once again, feature parity for FF/Chrome
=> feat(browserAction/alarms): add the complete APIs

README.md, global/index.d.ts
The `locked` state is not handled by Firefox at the moment
The supported subset is really small, but the complete API is not
exactly relevant for Firefox, as they are deemed a bit too powerful
(with good reasons)
Small bits exclusive to Firefox there
=> feat(apis): third batch done

README.md, global/index.d.ts
Not much here, this is full of deprecated APIs that Firefox did not
implement
Types are well defined here, no need for custom definitions
Short one, no difference between browsers here
Firefox does not handle `update()` nor `onButtonClicked` as they chose
to implement a simpler version of notifications
No quirks to speak of this time around
Many types created to avoid repetition in the events
The API makes it cumbersome to enforce the contract, this is postponed
to a later date
Small quirk in `create()` unaddressed, leave a `TODO` comment to address
it later
=> feat(apis): last batch before publication

README.md, global/index.d.ts
Creating some non existing types to enforce more strictness in the
`setIcon()` sidebar action
Small API as most of it functionality is based on manifest fields
rather than being active
Warning: This API will be available in Firefox 54. It is already
available in the nightly/dev channel, and is offered so that extension
developers can start working with it before the mainstream release
=> feat(sidebarAction): add the entire API

README.md, package.json
The API is pretty much complete, no need to put the status on top of
the README, nor is it needed to explicitely show every supported API
Patch number, as this only brought a new API while we're still under
version 1
=> chore(yarn): publication of a new version

global/index.d.ts
As per MDN's documentation https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/extensionTypes/InjectDetails
=> fix(extensionTypes): optional InjectDetails fields

global/index.d.ts
The `modifiers` field was added to the object, and is supported
from FF54 onwards
=> feat(contextMenus): update OnClickData

global/index.d.ts
Supported in FF54
As they are supported in FF54.
Integrated in FF54, has a few limitations still
Only a single event is available
Small API, with a single function. The documentation is really crap
though, as the callback in events are not defined at all and had to be
found in chrome documentation
Which means that if FF does not follow the same API, this won't work
=> feat(apis): update with the new FF54(beta) release

global/index.d.ts
Method should accept **tabId** not a **Tab**. ([documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/remove#Parameters))
=> Fix signature of browser.tabs.remove method

global/index.d.ts
As the function can have wildly different expectations and was clearly
not meant to be typed, enforce the contract by defining the function
with multiple types
Fix #28
=> fix(runtime): enforce sendMessage different APIs

global/index.d.ts
Feature added by firefox 55, see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus/create
=> Added command param to contextMenus.create()

global/index.d.ts
This is not clearly documented, but is in clear use in many
webextensions and in internal firefox code[1].
[1]: http://searchfox.org/mozilla-central/search?q=onMessage.addListener&case=true&path=*extension
=> runtime.onMessage.addListener accepts void funcs

global/index.d.ts
Properties discardable, autoDiscardable,
lastAccessed were absent, but documented as
available in MDN. However, autoDiscardable
appears to be unsupported.
>Error: Type error for parameter queryInfo
(Unexpected property "autoDiscardable") for
tabs.query.
=> Update Tab properties

global/index.d.ts
As stated on [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript#Browser_compatibility).
=> matchAboutBlank is now supported

global/index.d.ts
The function parameters for browser.tabs.reload() are optional as per https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/reload
=> Optional parameters for browser.tabs.reload()

global/index.d.ts
browser.bookmarks.getTree() has only optional parameter of callback.
=> fix parameters of browser.bookmarks.getTree() and getSubTree()

README.md, global/index.d.ts, package.json
Currently, all the messages and return values are typed as `any` or `object`. This change gives the consumer the option of providing explicit types, for additional type checking.
=> Add optional types to browser.runtime.sendMessage() and browser.tabs.sendMessage()

global/index.d.ts
StorageArea.get() parameter is optional.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/get
=> Add optional parameters to browser.storage.StorageArea.get()

global/index.d.ts
The [permissions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions) was still missing in web-ext-types.
=> Add permissions API

global/index.d.ts
For example if you have defined a type for the data stored, like this: 
``` ts
type settings = {
items: string[]
}
```
You can have it already typed out of the storage:
``` ts
browser.storage.sync.get<settings>("test").then((data) => {
data.items // data is typed with settings
})
```
Existing usage won't be bothered since `T` is a `StorageObject` by default.
=> Add the ability to type storage objects

global/index.d.ts
Thank you for providing this definition file! While using it I encountered some minor issues that I hereby provide fixes for:
* Fix issue with unregistering listeners from `browser.runtime.Port` events
* Add support for `browser.contentScripts`
* Add support for the “reset to default” invocation syntaxes of `browser.browserAction`
=> Several fixes for the type definitions

global/index.d.ts
`CreateDetails` has a `type` property: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/CreateDetails#type
=> Added type property to bookmark CreateDetails

global/index.d.ts
There were two properties missing: `allowScriptsToClose` and `titlePreface`.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create
Also please update the npm version :)
=> Added missing definitions

global/index.d.ts
Not sure why the authCredentials is commented out as unsupported. 
It is defined here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/BlockingResponse
=> Small fix to webRequest BlockingResponse

global/index.d.ts
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create#Parameters
First parameter (`id`) is optional and can be not used, eg:
```js
chrome.notifications.create({ type: 'basic', ... })
```
=> fix(notifications): overload "create" function

global/index.d.ts
Two new functions in the `browser.tabs` namespace `hide` and `show`. `browser.tabs.Tab` has a new `hidden` boolean property and `browser.tabs.query` got updated as well to reflect that.
=> Add support for tabhiding features.

global/index.d.ts
See details [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeTextColor) and [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/getBadgeTextColor).
=> Add support for setBadgeTextColor and getBadgeTextColor.

global/index.d.ts
[Cookie](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/Cookie) type now have a `sameSite` and `firstPartyDomain` (I put it as optional since other browsers do not support this attribute).
Most of the cookie API now takes in an optional parameter for `firstPartyDomain`.
There's now a [removeLocalStorage()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/removeLocalStorage) in browsingData.
RemovalOptions now has an extra parameter for hostnames that is only applied to [removeCookies() and removeLocalStorage()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/RemovalOptions).
=> Update browser.cookies and browser.browsingData

global/index.d.ts
Function overload is needed since both arguments are optional. See the [example](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connect#Examples) on MDN.
=> Fix runtime.connect argument
