README.md, global/index.d.ts
=> feat(omnibox): entire API done

README.md, global/index.d.ts
=> feat(commands/events): add both APIs

package.json
=> chore(yarn): update version number

README.md
Package is published on npm, reflect that on the documentation with
badge showing the latest version and the install instructions
=> docs(README): add the npm package

global/index.d.ts, package.json
The real prototype exposes the arguments as optional
From `0.1.0` to `0.1.1` due to the fix
Fix #12
=> ### fix(extension): update getViews() arguments

README.md, global/index.d.ts
Some polishing can happen later on, as the contract can be made
stricter with intersection/union types
Update documentation to reflect completeness
=> feat(webRequest): finally add the complete API

global/index.d.ts
Add the `id` field to the createProperties object
=> feat(contextMenus): update createProperties

package.json
New APIs (devtools/webRequest/) and API fixes
=> chore(yarn): update to version 0.2.3

global/index.d.ts
Add the `selection` value to `ContextType` and make the second parameter for `create()` optional.
=> feat(contextMenus): update ContextType and create()

global/index.d.ts
Add a `StorageResults` type and replace the fulfilled Promise type for `get()` with it.
=> feat(storage): add StorageResults Promise type

package.json
Soundness fix, so while technically a breaking change, it should keep
working unless API usage was wrong
=> chore(npm): update version to 0.3.1

README.md
Given the current situation where Mozilla chose to use Google Analytics
tools inside their product, I do not want to spend time working on a
browser that chose to deliberately disregard their users choices' (as
even with tracking disabled, that tracking happens regardless).
=> docs(README): notice of halted development

global/index.d.ts
=> Add theme API

global/index.d.ts
Add type property to browser.bookmarks.BookmarkTreeNode and add open() and close() to broser.sidebarAction
=> Add property and type to bookmarks and add methods to sidebarAction.

global/index.d.ts
"INDOW_ID_CURRENT" should be "WINDOW_ID_CURRENT"
=> Fix spelling mistake INDOW_ID_CURRENT

global/index.d.ts
That way there's a consistent style throughout, no matter what.
I don't intend to force contributions to go through that additional step, so I'll do that manually (for now).
=> style(all): format with prettier

global/index.d.ts
@alexander255 Could you confirm that version is still working for you? If not, I'd love to see the affected code, thanks!
=> fix(browserAction): stricter setIcon typing

global/index.d.ts
Should cover [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find) completely.
=> Add browser.find namespace.

global/index.d.ts
- Use the `Listener` wrapper.
- Change `message` to `any`.
- `postMessage` with generic.
=> Update runtime.Port types

global/index.d.ts
See <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set#Parameters>.
=> add missing sameSite and value on cookies.set

global/index.d.ts
Minor fix, visitTime was incorrectly capitalized!
=> Fix case on VisitItem.visitTime
